### PR TITLE
Fix docker env

### PR DESCRIPTION
**Pull request by loleg**
Addresses issue in the Docker Compose environment.

### CODE REVIEW

**Review by n0rdlicht — CHANGES_REQUESTED** [review]
Please also revert the yarn.lock changes before we merge into main.

**Comment by loleg** [comment]
Oops! Done.

**Review by n0rdlicht — APPROVED** [review]

**Comment by n0rdlicht** [comment]
@yvess any objections on your end on extracting these into env variables?

**Comment by loleg** [comment]
I don't think the failing tests have anything to do with my changes - same logs as in #28

**Pull request merged**
