### PR TITLE
Improve API performance when querying annotations

### LINKED ISSUE #337: Performance of annotations in `main-participation`
Depending on the machine a significant query slow down is noticeable, once a certain number (anywhere between 100 and 1000) published annotations per workspace is reached. While a couple of annotations stay sub 1 second total load time, this can reach up to a couple of seconds for 100 annotations and go up from there depending on the host machine of the django backend.

Research so far:
- queries only see significant slow downs when `category` and/or `attachments` are included
- similar (also "join") sql queries on the same machine and database do not see slow downs
- django middlewares, as hinted at in https://github.com/graphql-python/graphene-django/issues/810, cc @luisgisler 
- potential graphene n+1 issues: https://github.com/graphql-python/graphene/issues/358#, see also https://kulor.medium.com/pragmatic-performance-tuning-django-e5218abeb9e6

### PR DESCRIPTION
**Pull request by n0rdlicht**
Added https://github.com/tfoxy/graphene-django-optimizer to improve performance when loading annotations during a workspace query. Closes #337

### CODE REVIEW

**Comment by n0rdlicht** [comment]
@yvess please have a look, if you think adding the graphene-django-optimizer package makes sense here or if there is a simpler way of fixing the issue. We could test these changes/images in an upcoming deployment tag next Monday, November 15. I did see you started working on the images over in 6ef826a3. I can merge these here to start from the same base going forward.

**Comment by yvess** [comment]
yes I think it makes sense to use this package. Did you already test it if it improves the performance? It also is good to merge 6ef826a3dda1f39f1e7bb926f57eda7612f03a7f into this branch before creating a new docker image. I can create the docker image if you want. Sometimes the cache doesn't work good if you use a different machine so I suggest that I build the docker image, or you can first try it, and when the layer caching works you can build it

**Comment by n0rdlicht** [comment]
Haven't run extensive benchmarks yet, but did test with 1000 annotations. Response times roughly halved with adding the package and changes in this PR. I had roughly 5 seconds originally and it went down to 2.5. For smaller sets (around 100) from somewhere above 2 to under 1 second.

Docker images. I did have some issues building the image indeed, only managed with `alpine:3.14.2` instead of the previously used `alpine:3.13.5`.

I integrated changes from 6ef826a (e.g. for `django/docker/django/Dockerfile`) now, and did a `arm64` and `amd64` build that is also pushed to [hub.docker.com/r/smartuse/gemeindescan-webui-django](http://hub.docker.com/r/smartuse/gemeindescan-webui-django) as `3.1.12b`. Give it a test. I will try a deployment over the weekend to see if the optimizer improves performance in production.

**Comment by n0rdlicht** [comment]
Query times workspace + snapshot + annotations, 154 published annotations:
- w/o optimizer: ca. 5.9 seconds
- w/ optimizer: ca. 3.5 seconds

Will do a merge into `main-participation`.

**Pull request merged**
