### PR TITLE
Switch to MapLibre

### PR DESCRIPTION
**Pull request by loleg**
This is an experimental PR which swaps out the (actually now [discontinued](https://docs.mapbox.com/help/glossary/mapbox-js/) mapbox.js) in favour of [MapLibre](https://github.com/maplibre/maplibre-gl-js/).

See also:
- [Discussion of bundle sizes](https://github.com/maplibre/maplibre-gl-js/issues/59)
- [Question about Mapbox-GL-Leaflet](https://github.com/mapbox/mapbox-gl-leaflet/issues/137)
- https://observablehq.com/@rkaravia/hello-swisstopo-light-base-map

### CODE REVIEW

**Comment by n0rdlicht** [comment]
Thanks Oleg for looking into this. I will check later today. Please also have a look at #51 and #52 for the overarching topic of how to re-organize configuration options.

**Comment by n0rdlicht** [comment]
Couldn't get it the vue part to work yet. How did you install the new dependencies inside the container?

In general: we are currently using the Mapbox Wrapper around Leaflet JS, not mapbox-gl. Since we only have very light vector rendering needs. Also, every vector based library comes with their own way of defining styles that are usually incompatible with our current snapshot spec approach which combines geometry and styling in the `snapshot.resource`. We also added circle layers specifically based on the Leaflet API. We either need to rethink the spec to add a layer of abstraction or build translators for old snapshots if we switch to a different approach.

**Comment by loleg** [comment]
Sounds like a topic we should do some guru meditation on soon. Have a nice
weekend!

**Review by n0rdlicht — CHANGES_REQUESTED** [review]
Let's pivot this PR to include the environment variable and readme changes and create a new issue on MapLibre.

**Comment by loleg** [comment]
I've moved the Docker changes from this PR into #67

**Comment by wipfli** [comment]
We are working on `maplibre-gl-leaflet` at https://github.com/maplibre/maplibre-gl-leaflet. We plan to publish a package at `@maplibre/maplibre-gl-leaflet` on NPM. Maybe this can be useful for your project.

**Comment by n0rdlicht** [comment]
Continued in https://github.com/cividi/spatial-data-package-platform/issues/452.

**Pull request closed without merging**
